# Generated by Django 2.1.5 on 2019-02-24 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('shop_no', models.AutoField(primary_key=True, serialize=False)),
                ('shop_nm', models.CharField(max_length=50)),
                ('place_id', models.IntegerField(null=True)),
                ('restaurant_type', models.CharField(max_length=3, null=True)),
                ('group_seat_yn', models.CharField(default='N', max_length=1, null=True)),
                ('type', models.CharField(max_length=1, null=True)),
                ('hash_tag', models.CharField(max_length=200, null=True)),
                ('shop_img', models.CharField(max_length=100, null=True)),
                ('reg_id', models.CharField(max_length=25)),
                ('reg_dt', models.DateField(blank=True, default=datetime.datetime.now)),
                ('chg_id', models.CharField(max_length=25, null=True)),
                ('chg_dt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
