# Generated by Django 2.1.5 on 2019-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='shop_img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
